spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/cmfz?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.ag.repository: debug
mybatis-plus:
  type-aliases-package: com.ag.entity
  mapper-locations: classpath:mapper/*.xml
init:
  app: 1